### ISSUE TITLE
Writing to stdout no longer works in python3 port

### ISSUE THREAD

**Issue by andyjpb** [FriedrichFroebel/didjvu#34]
This used to work in the Python 2 version:

```
$ ~/.local/bin/didjvu encode out1.pnm-1 > out1.pnm.djvu
out1.pnm-1:
- reading image
- converting to DjVu
Traceback (most recent call last):
  File "/home/local/andyjpb/.local/bin/didjvu", line 8, in <module>
    sys.exit(main())
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/__main__.py", line 7, in main
    Main(prog=prog)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/didjvu.py", line 218, in __init__
    parser.parse_arguments(actions=self)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/cli.py", line 336, in parse_arguments
    return action(options)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/didjvu.py", line 300, in encode
    parallel_for(options, self.encode_one, options.input, options.masks, options.output, options.xmp_output)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/didjvu.py", line 75, in parallel_for
    function(options, *args)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/didjvu.py", line 329, in encode_one
    bytes_out = fs.copy_file(djvu_file, output)
  File "/home/local/andyjpb/.local/lib/python3.9/site-packages/didjvu/fs.py", line 32, in copy_file
    output_file.write(block)
TypeError: write() argument must be str, not bytes
```

However, this does work:

```
$ ~/.local/bin/didjvu encode out1.pnm-1 -o out1.pnm.djvu
out1.pnm-1:
- reading image
- converting to DjVu
- 0.036 bits/pixel; 675.717:1, 99.85% saved, 26114417 bytes in, 38647 bytes out
```

**Comment by FriedrichFroebel** [comment]
Thanks for the report. This has been fixed on GitHub: https://github.com/FriedrichFroebel/didjvu/commit/065af70ce5b47208debd9a086ff8d9486ddd39a9.
