### ISSUE TITLE
Replace `nose` for tests

### ISSUE THREAD

**Issue by FriedrichFroebel** [FriedrichFroebel/didjvu#6]
We currently use `nose` for running the tests. As this package is officially unmaintained, our tests fail on Python 3.10:

```python3
python3 didjvu --test --verbose tests/
Traceback (most recent call last):
  File "/home/runner/work/didjvu/didjvu/didjvu", line 25, in <module>
    didjvu.main()
  File "/home/runner/work/didjvu/didjvu/lib/didjvu.py", line 203, in __init__
    parser.parse_args(actions=self)
  File "/home/runner/work/didjvu/didjvu/lib/cli.py", line 308, in parse_args
    o = argparse.ArgumentParser.parse_args(self)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/argparse.py", line 2067, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/argparse.py", line 2007, in consume_optional
    take_action(action, args, option_string)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/argparse.py", line 1935, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/runner/work/didjvu/didjvu/lib/cli.py", line 129, in __call__
    nose.main(argv=argv)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 183, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
make: *** [Makefile:53: test] Error 1
```

We should therefore have a look at the maintained alternatives (see https://github.com/nose-devs/nose/issues/1099 as well). For now, we should probably be able to monkey-patch it using https://stackoverflow.com/a/70641487/.

**Comment by rmast** [comment]
I thought I had some nose run tests on 22.04, just with these commands:

```
sudo apt install python3-pip gir1.2-gexiv2-0.10 libexempi-dev libboost-python-dev libexiv2-dev libpng-dev libtiff-dev djvulibre-bin exiv2 python3-pil
```

```
pip install py3exiv2
pip install python-xmp-toolkit
pip install nose
```

**Comment by FriedrichFroebel** [comment]
According to my tests with CI, this currently affects Python 3.10 only. As Ubuntu 22.04 still uses Python 3.9 according to https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=python3-dev&searchon=names, you should have been safe.

Unfortunately, this *nose* issue seems to occur differently depending on the setup, where your Python version comes from and how you install it. For this reason, it might work in certain setup, while it does not for others. (Similar example from CI: Everything is built on Ubuntu 20.04, shipping with Python 3.8 by default. For this reason we cannot use the convenient *python3-x* packages there and have to build *Boost.Python* manually which you normally do not have to.)

This does not change anything about *nose* being deprecated for quite some time now. Migrating to some up-to-date test runner is an open task for this reason - whether we actually face issues with *nose* or not in our setup.

**Comment by rmast** [comment]
I already dropped the Azure Jammy-image, however for as far as I remember I saw Python 3.10.

https://linuxconfig.org/ubuntu-22-04-features-and-release-date#:~:text=Python%203.10.&text=0%20version%20will%20be%20shipped,fit%20for%20your%20programming%20needs.

I can retest it.

**Comment by FriedrichFroebel** [comment]
No need to re-test it - if it does not work for one setup, we will have to evaluate alternatives anyway, as outlined in my last comment.

**Comment by rmast** [comment]
> For this reason we cannot use the convenient _python3-x_ packages there and have to build _Boost.Python_ manually which you normally do not have to.)

Boost.Python missing the 3.10 support was the reason I found Jammy, as that has 3.10 support in it's Boost.Python apt-package. I didn't put the effort in building it, I preferred a distribution that comes closest to the upcoming 22.04 and that appears to be the developer version of 22.04.

**Comment by rmast** [comment]
> I already dropped the Azure Jammy-image, however for as far as I remember I saw Python 3.10. ... I can retest it.

I now retested with a daily image of a few days back. You're right about the nose incompatibility. I think I was confused by 3.9.10.

**Comment by FriedrichFroebel** [comment]
Judging from a quick glance and some quick testing, replacing *nose* with plain *unittest* (and *coverage.py*) means some larger refactoring of the tests. Reason is that all assertion methods are imported from *nose* and all legacy code uses method-based tests instead of the *unittest* module of the standard library.

The migration process probably looks like this:

* Create a custom test case class deriving from *unittest.TestCase* which includes our custom assertions.
* Migrate all existing tests to a class-based structure, using our custom test case as base class.
* Replace the *nose* runners for tests and coverage with *unittest.main()*.
* Check if `tests.tools.fork_isolation` is required or can be omitted.
